### ISSUE TITLE
Unkown encoding "BBB"

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [jonschlinkert/write#2]
In the master branch, the code is using `fs.writeFileSync("file.txt", {}, "BBB");`, but the [node docs says](https://nodejs.org/api/fs.html#fs_fs_writefilesync_file_data_options) that the signature is `fs.writeFileSync("file.txt", "BBB")`.

Am I missing something?

Using: `node v5.7.0`.

**Comment by FagnerMartinsBrack** [comment]
Last time that code was changed was [11 days ago](https://github.com/jonschlinkert/write/commit/2ebc61f1dfd74cb522675c96308b9c2066e15d94#diff-168726dbe96b3ce427e7fedce31bb0bcR75).

**Comment by jonschlinkert** [comment]
sorry for the late response, looking into it now.

**Comment by jonschlinkert** [comment]
fixed and published/tagged as 0.3.1. thanks for the heads up

**Comment by FagnerMartinsBrack** [comment]
I guess the code could use some tests to prevent regression, right?

**Comment by jonschlinkert** [comment]
that would be great thanks!
