### ISSUE TITLE
mkdirp is busted

### ISSUE THREAD

**Issue by phated** [jonschlinkert/write#3]
I've completely reimplemented mkdirp in vinyl-fs because it is fundamentally broken cross-platform.   Just a heads up.

Ref https://github.com/gulpjs/vinyl-fs/blob/master/lib/file-operations.js#L269-L327

**Comment by jonschlinkert** [comment]
good to know, thanks. 

I've been trying to update a few related fs/path modules over the past couple of days. this is on my todo list now too

**Comment by jonschlinkert** [comment]
Hmm, after looking at your code I'd prefer not to have to re-engineer all of that and maintain it. any chance of externalizing that code?

**Comment by phated** [comment]
@jonschlinkert I considered it when writing it but thought it was too specific to my use cases (plus I didn't want to find a name/try to take over mkdirp, or maintain it separately).  You might not need to handle the edge cases that node & mkdirp don't handle properly, not sure.

**Comment by jonschlinkert** [comment]
K, I'll look into it more and review issues on mkdirp. thanks

**Comment by phated** [comment]
Btw, I created https://github.com/gulpjs/fs-mkdirp-stream

**Comment by jonschlinkert** [comment]
Okay, I reviewed and it looks like we wouldn't be able to use that module here without also having to use `mkdirp` anyway since we still need to make directories with non-stream methods.  Since we haven't had any issues about this, I'm going to close for now, but I'm always open to making improvements or discussing further.

**Comment by phated** [comment]
Huh?  I made the mkdirp available as `fs-mkdirp-stream/mkdirp`...

**Comment by jonschlinkert** [comment]
Oh, just not documented I guess? At a glance, I didn't see it.

**Comment by phated** [comment]
Sorry, not sync.  You said non-stream so I pointed to the non-stream async method.

**Comment by jonschlinkert** [comment]
got it. would you be opposed to adding a sync method?

**Comment by phated** [comment]
I don't really want to maintain that API surface (which is also why the `mkdirp.js` file isn't documented). I think your usage of `mkdirp` will be fine for most people (it's really popular, after all).
