### ISSUE TITLE
Uncaught TypeError: xfs.mkdir is not a function

### ISSUE THREAD

**Issue by jwmann** [jonschlinkert/write#5]
`Uncaught TypeError: xfs.mkdir is not a function  index.js?0191:27`

I'm using it as per the docs
```
      writeFile('Report.csv', csv, function(err) {
        if (err) throw err;
      });
```
csv is a valid object using the `json2csv` module

Not sure what I'm missing here.
Could be related to #3 ?

**Comment by jonschlinkert** [comment]
Is that all of the code necessary to reproduce the bug? That error message implies that `mkdirp` is trying to use a custom `.mkdir` function, which would be user-defined on the options. Since you aren't showing anything like that in your example, I'll need more information to debug.

**Comment by jonschlinkert** [comment]
> Could be related to #3 ?

Um, no I don't think so.  I think you were either doing something that isn't shown in your example, or another lib is responsible. That error isn't related to this library.

**Comment by FrancisVila** [comment]
I get the same message: 
TypeError: xfs.mkdir is not a function 
C:/react/prerequisites/node_modules/mkdirp/index.js:31
31 | xfs.mkdir(p, mode, function (er) { 

I'm trying to use **writeFile** from the **write** module, here is the code I use in the render() function of App.js
var writeFile = require('write');
    writeFile('foo.txt', 'This is content...', function(err) {
      if (err) console.log(err);
    });

**Comment by jonschlinkert** [comment]
I'll need more information, this should have been fixed. 

- What version of `write` are you using? 
- Node.js version? 
- OS?

**Comment by FrancisVila** [comment]
write@1.0.3
node v8.12.0
Windows 10 Enterprise v.1803 Installed on 2018-10-09 OS build 17134.407

**Comment by jonschlinkert** [comment]
Again, looks like this error is not related to this library. It looks like an error from `mkdirp` and must have something to do with options being passed, or something else beyond the control of this library.
